// src/demoData.js – Windoform Demo Data

const sellers = ["Cem Yüksel", "Mehmet Kaya", "Ayşe Demir", "Emre Özkan"];

export const demoCustomers = [
  { name: "Thomas Schneider", company: "Fenster König GmbH", position: "Geschäftsführer", email: "t.schneider@fensterkoenig.de", phone: "+49 89 123 456", status: "won", source: "Fensterbau Frontale 2026", notes: "Interesse an Premium Fenstergriff-Serie. Budget ca. 50.000€/Jahr." },
  { name: "Fatih Yılmaz", company: "Doğuş Yapı A.Ş.", position: "Satın Alma Müdürü", email: "fatih@dogusyapi.com.tr", phone: "+90 212 555 0101", mobile: "+90 532 111 2233", status: "negotiation", source: "Fensterbau Frontale 2026", notes: "Großes Bauprojekt in Istanbul. 200 Wohneinheiten." },
  { name: "Laura Weber", company: "Bauelemente Plus AG", position: "Einkaufsleiterin", email: "l.weber@bauelementeplus.de", phone: "+49 711 987 654", status: "offer", source: "BAU München 2025", notes: "Will Muster bestellen. Nachfolge-Meeting in KW 14." },
  { name: "Hasan Demir", company: "Özdemir Pencere Ltd.", position: "Genel Müdür", email: "hasan@ozdemirvepencere.com.tr", phone: "+90 232 444 5566", mobile: "+90 542 333 4455", status: "won", source: "Fensterbau Frontale 2026", notes: "Stammkunde seit 2020. Jährlicher Umsatz ca. 120.000€." },
  { name: "Marcus Hoffmann", company: "Hoffmann Bau GmbH", position: "Projektleiter", email: "m.hoffmann@hoffmann-bau.de", phone: "+49 30 456 789", status: "contact", source: "Website Anfrage", notes: "Großprojekt München. 500 Fenstereinheiten." },
  { name: "Elif Arslan", company: "Arslan İnşaat", position: "Teknik Müdür", email: "elif@arslaninsaat.com.tr", phone: "+90 216 777 8899", mobile: "+90 555 666 7788", status: "lead", source: "Fensterbau Frontale 2026" },
  { name: "Stefan Müller", company: "Müller Fensterwerk", position: "Inhaber", email: "s.mueller@mueller-fenster.de", phone: "+49 40 111 222", status: "won", source: "Empfehlung", notes: "Kleiner Betrieb, aber regelmäßige Bestellungen." },
  { name: "Carlos Garcia", company: "Ventanas Madrid S.L.", position: "Director Comercial", email: "carlos@ventanasmadrid.es", phone: "+34 91 555 1234", status: "offer", source: "BAU München 2025", notes: "Spanischer Markt. Potenzial für Exklusiv-Vertrieb." },
  { name: "Ahmet Çelik", company: "Çelik PVC", position: "Kurucu", email: "ahmet@celikpvc.com.tr", phone: "+90 312 999 0000", mobile: "+90 533 222 3344", status: "won", source: "Bestandskunde", notes: "Top-Kunde. Monatliche Lieferungen seit 2019." },
  { name: "Andrea Fischer", company: "Fischer Bauelemente", position: "Vertriebsleiterin", email: "a.fischer@fischer-bau.de", phone: "+49 69 333 444", status: "negotiation", source: "Messe Kontakt", notes: "Verhandlung über Jahresrahmenvertrag." },
  { name: "Murat Koç", company: "Koç Alüminyum", position: "İhracat Müdürü", email: "murat@kocaluminyum.com.tr", phone: "+90 224 888 7766", mobile: "+90 544 111 2233", status: "contact", source: "LinkedIn" },
  { name: "Pierre Dubois", company: "Fenêtres de France", position: "Directeur des Achats", email: "p.dubois@fenetresfrance.fr", phone: "+33 1 44 55 66 77", status: "lead", source: "Fensterbau Frontale 2026" },
];

export const demoProducts = [
  { name: "Fenstergriff Premium Edelstahl", sku: "WF-FG-001", price: 24.90, category: "Fenstergriffe", description: "Hochwertiger Edelstahl-Fenstergriff, gebürstet. 7mm Vierkantstift." },
  { name: "Fenstergriff Standard Weiß", sku: "WF-FG-002", price: 8.50, category: "Fenstergriffe", description: "Standard-Fenstergriff in RAL 9016 Weiß." },
  { name: "Fenstergriff Secustik Silber", sku: "WF-FG-003", price: 32.00, category: "Fenstergriffe", description: "Abschließbarer Sicherheits-Fenstergriff mit Secustik-Funktion." },
  { name: "Dichtung EPDM Universal", sku: "WF-DI-001", price: 2.80, category: "Dichtungen", description: "Universal EPDM Fensterdichtung. Pro Meter. -40°C bis +120°C." },
  { name: "Dichtung TPE Premium", sku: "WF-DI-002", price: 4.20, category: "Dichtungen", description: "Premium TPE Dichtung für hohe Beanspruchung. Pro Meter." },
  { name: "Eckumlenkung Standard", sku: "WF-BE-001", price: 12.50, category: "Beschläge", description: "Standard-Eckumlenkung für Dreh-Kipp-Fenster." },
  { name: "Scherenlager 12/20-13", sku: "WF-BE-002", price: 18.90, category: "Beschläge", description: "Scherenlager für Flügelgewichte bis 130kg." },
  { name: "Schließplatte Universal", sku: "WF-BE-003", price: 3.40, category: "Beschläge", description: "Universal-Schließplatte für alle gängigen Systeme." },
  { name: "Türdrücker-Garnitur Design", sku: "WF-TG-001", price: 45.00, category: "Türbeschläge", description: "Moderne Türdrücker-Garnitur in Edelstahl matt." },
  { name: "Balkontürgriff Olive", sku: "WF-TG-002", price: 15.80, category: "Türbeschläge", description: "Balkontür-Olivengarnitur in Weiß oder Silber." },
  { name: "Rollenlager Kunststoff", sku: "WF-RL-001", price: 6.90, category: "Rollenlager", description: "Rollenlager für Kunststoff-Fenster. Set = 2 Stück." },
  { name: "Ausstellschere 350mm", sku: "WF-AS-001", price: 22.50, category: "Beschläge", description: "Ausstellschere für Oberlichtfenster, 350mm." },
];

export const demoDeals = [
  { title: "Jahresrahmenvertrag 2026", customerName: "Fenster König GmbH", assignedName: "Cem Yüksel", amount: 85000, status: "won", productList: "Fenstergriff Premium x2000, Dichtung EPDM x5000m", notes: "Vertrag bis Ende 2026. Quartalslieferungen." },
  { title: "Bauprojekt Istanbul Towers", customerName: "Doğuş Yapı A.Ş.", assignedName: "Mehmet Kaya", amount: 125000, status: "negotiation", productList: "Fenstergriff Secustik x800, Eckumlenkung x1200, Scherenlager x600", notes: "Lieferung in 3 Tranchen. Erste Tranche April 2026." },
  { title: "Erstbestellung Bauelemente Plus", customerName: "Bauelemente Plus AG", assignedName: "Cem Yüksel", amount: 22000, status: "offer", productList: "Fenstergriff Standard x500, Dichtung TPE x2000m", notes: "Muster gesendet. Warten auf Freigabe." },
  { title: "Stammkunden-Nachbestellung Q1", customerName: "Özdemir Pencere Ltd.", assignedName: "Ayşe Demir", amount: 38000, status: "won", productList: "Fenstergriff Premium x800, Schließplatte x2000, Rollenlager x500" },
  { title: "Großprojekt München-Ost", customerName: "Hoffmann Bau GmbH", assignedName: "Cem Yüksel", amount: 67000, status: "contact", productList: "Diverse Beschläge", notes: "Angebot wird vorbereitet. Termin am 25.03." },
  { title: "Spanien Pilotbestellung", customerName: "Ventanas Madrid S.L.", assignedName: "Emre Özkan", amount: 15000, status: "offer", productList: "Fenstergriff Premium x200, Türdrücker Design x100" },
  { title: "Monatliche Lieferung März", customerName: "Çelik PVC", assignedName: "Ayşe Demir", amount: 42000, status: "won", productList: "Fenstergriff Standard x1000, Eckumlenkung x800, Dichtung EPDM x3000m" },
  { title: "Müller Fenster - Nachbestellung", customerName: "Müller Fensterwerk", assignedName: "Mehmet Kaya", amount: 8500, status: "won", productList: "Fenstergriff Premium x150, Balkontürgriff x80" },
  { title: "Rahmenvertrag Verhandlung", customerName: "Fischer Bauelemente", assignedName: "Cem Yüksel", amount: 95000, status: "negotiation", productList: "Gesamtsortiment", notes: "Jahresvolumen. Preisverhandlung läuft." },
  { title: "Çelik PVC Sonderbestellung", customerName: "Çelik PVC", assignedName: "Ayşe Demir", amount: 18500, status: "won", productList: "Ausstellschere x400, Scherenlager x300" },
  { title: "Koç Alüminyum Erstanfrage", customerName: "Koç Alüminyum", assignedName: "Mehmet Kaya", amount: 30000, status: "contact", productList: "Beschläge-Set", notes: "Muster angefordert." },
];

export const demoTasks = [
  { title: "Angebot Bauelemente Plus nachfassen", customerName: "Bauelemente Plus AG", dueDate: "2026-03-15", priority: "high", done: false, assignedName: "Cem Yüksel" },
  { title: "Vertragsentwurf Fischer prüfen", customerName: "Fischer Bauelemente", dueDate: "2026-03-18", priority: "urgent", done: false, assignedName: "Cem Yüksel" },
  { title: "Muster nach Spanien versenden", customerName: "Ventanas Madrid S.L.", dueDate: "2026-03-12", priority: "medium", done: false, assignedName: "Emre Özkan" },
  { title: "Istanbul Projekt Liefertermine klären", customerName: "Doğuş Yapı A.Ş.", dueDate: "2026-03-20", priority: "high", done: false, assignedName: "Mehmet Kaya" },
  { title: "Hoffmann Bau Termin vorbereiten", customerName: "Hoffmann Bau GmbH", dueDate: "2026-03-25", priority: "medium", done: false, assignedName: "Cem Yüksel" },
  { title: "Quartalsabrechnung Özdemir", customerName: "Özdemir Pencere Ltd.", dueDate: "2026-03-31", priority: "low", done: false, assignedName: "Ayşe Demir" },
  { title: "Messe-Leads nacharbeiten", customerName: "", dueDate: "2026-03-14", priority: "high", done: true, assignedName: "Cem Yüksel" },
  { title: "Produktkatalog aktualisieren", customerName: "", dueDate: "2026-03-10", priority: "medium", done: true, assignedName: "Emre Özkan" },
  { title: "Koç Alüminyum Muster senden", customerName: "Koç Alüminyum", dueDate: "2026-03-22", priority: "medium", done: false, assignedName: "Mehmet Kaya" },
  { title: "Pierre Dubois Follow-up Call", customerName: "Fenêtres de France", dueDate: "2026-03-19", priority: "low", done: false, assignedName: "Emre Özkan" },
];

// Production data – last 30 days of realistic Windoform production
export const demoProduction = [
  // März 2026
  { product: "Ege Akustik", ral: "9016", quantity: 850, date: "2026-03-11", shift: "Tag", notes: "Vollauslastung" },
  { product: "Ege Akustik", ral: "9016", quantity: 620, date: "2026-03-11", shift: "Nacht", notes: "" },
  { product: "Ege Akustik", ral: "7016", quantity: 340, date: "2026-03-11", shift: "Tag", notes: "Anthrazit Sondercharge" },
  { product: "Fenstergriff Premium Edelstahl", ral: "", quantity: 1200, date: "2026-03-11", shift: "Tag", notes: "" },
  { product: "Fenstergriff Standard", ral: "9016", quantity: 2400, date: "2026-03-11", shift: "Tag", notes: "" },
  { product: "Fenstergriff Standard", ral: "9016", quantity: 1800, date: "2026-03-11", shift: "Nacht", notes: "" },
  { product: "Ege Akustik", ral: "9016", quantity: 920, date: "2026-03-10", shift: "Tag", notes: "" },
  { product: "Ege Akustik", ral: "9016", quantity: 580, date: "2026-03-10", shift: "Nacht", notes: "" },
  { product: "Ege Akustik", ral: "8017", quantity: 220, date: "2026-03-10", shift: "Tag", notes: "Schokobraun" },
  { product: "Fenstergriff Premium Edelstahl", ral: "", quantity: 1100, date: "2026-03-10", shift: "Tag", notes: "" },
  { product: "Fenstergriff Standard", ral: "9016", quantity: 2200, date: "2026-03-10", shift: "Tag", notes: "" },
  { product: "Dichtung EPDM Universal", ral: "", quantity: 5000, date: "2026-03-10", shift: "Tag", notes: "5000 Meter" },
  { product: "Ege Akustik", ral: "9016", quantity: 780, date: "2026-03-09", shift: "Tag", notes: "" },
  { product: "Ege Akustik", ral: "9016", quantity: 650, date: "2026-03-09", shift: "Nacht", notes: "" },
  { product: "Fenstergriff Secustik", ral: "9016", quantity: 400, date: "2026-03-09", shift: "Tag", notes: "Sicherheits-Serie" },
  { product: "Fenstergriff Standard", ral: "9016", quantity: 2600, date: "2026-03-09", shift: "Tag", notes: "" },
  { product: "Ege Akustik", ral: "9016", quantity: 900, date: "2026-03-08", shift: "Tag", notes: "" },
  { product: "Ege Akustik", ral: "7016", quantity: 280, date: "2026-03-08", shift: "Tag", notes: "" },
  { product: "Fenstergriff Premium Edelstahl", ral: "", quantity: 950, date: "2026-03-08", shift: "Tag", notes: "" },
  { product: "Fenstergriff Standard", ral: "9016", quantity: 2100, date: "2026-03-08", shift: "Tag", notes: "" },
  { product: "Eckumlenkung Standard", ral: "", quantity: 1500, date: "2026-03-08", shift: "Tag", notes: "" },
  { product: "Ege Akustik", ral: "9016", quantity: 870, date: "2026-03-07", shift: "Tag", notes: "" },
  { product: "Ege Akustik", ral: "9016", quantity: 710, date: "2026-03-07", shift: "Nacht", notes: "" },
  { product: "Fenstergriff Standard", ral: "9016", quantity: 2500, date: "2026-03-07", shift: "Tag", notes: "Großauftrag Çelik PVC" },
  { product: "Scherenlager 12/20-13", ral: "", quantity: 800, date: "2026-03-07", shift: "Tag", notes: "" },
  { product: "Ege Akustik", ral: "9016", quantity: 830, date: "2026-03-06", shift: "Tag", notes: "" },
  { product: "Ege Akustik", ral: "9005", quantity: 180, date: "2026-03-06", shift: "Tag", notes: "Tiefschwarz Sonderauftrag" },
  { product: "Fenstergriff Premium Edelstahl", ral: "", quantity: 1050, date: "2026-03-06", shift: "Tag", notes: "" },
  { product: "Fenstergriff Standard", ral: "9016", quantity: 2300, date: "2026-03-06", shift: "Tag", notes: "" },
  { product: "Dichtung TPE Premium", ral: "", quantity: 3500, date: "2026-03-06", shift: "Tag", notes: "3500 Meter" },
  { product: "Ege Akustik", ral: "9016", quantity: 910, date: "2026-03-05", shift: "Tag", notes: "" },
  { product: "Ege Akustik", ral: "9016", quantity: 600, date: "2026-03-05", shift: "Nacht", notes: "" },
  { product: "Fenstergriff Standard", ral: "9016", quantity: 2000, date: "2026-03-05", shift: "Tag", notes: "" },
  { product: "Türdrücker-Garnitur Design", ral: "", quantity: 350, date: "2026-03-05", shift: "Tag", notes: "" },
  { product: "Ege Akustik", ral: "9016", quantity: 840, date: "2026-03-04", shift: "Tag", notes: "" },
  { product: "Ege Akustik", ral: "7016", quantity: 310, date: "2026-03-04", shift: "Tag", notes: "" },
  { product: "Fenstergriff Premium Edelstahl", ral: "", quantity: 1150, date: "2026-03-04", shift: "Tag", notes: "" },
  { product: "Fenstergriff Standard", ral: "9016", quantity: 2200, date: "2026-03-04", shift: "Tag", notes: "" },
  { product: "Balkontürgriff Olive", ral: "", quantity: 600, date: "2026-03-04", shift: "Tag", notes: "" },
  { product: "Ege Akustik", ral: "9016", quantity: 890, date: "2026-03-03", shift: "Tag", notes: "" },
  { product: "Ege Akustik", ral: "9016", quantity: 670, date: "2026-03-03", shift: "Nacht", notes: "" },
  { product: "Fenstergriff Standard", ral: "9016", quantity: 2400, date: "2026-03-03", shift: "Tag", notes: "" },
  { product: "Schließplatte Universal", ral: "", quantity: 2000, date: "2026-03-03", shift: "Tag", notes: "" },
  { product: "Ausstellschere 350mm", ral: "", quantity: 450, date: "2026-03-03", shift: "Tag", notes: "" },
  // Februar tail
  { product: "Ege Akustik", ral: "9016", quantity: 860, date: "2026-02-28", shift: "Tag", notes: "" },
  { product: "Ege Akustik", ral: "9016", quantity: 590, date: "2026-02-28", shift: "Nacht", notes: "" },
  { product: "Fenstergriff Standard", ral: "9016", quantity: 2100, date: "2026-02-28", shift: "Tag", notes: "" },
  { product: "Fenstergriff Premium Edelstahl", ral: "", quantity: 980, date: "2026-02-28", shift: "Tag", notes: "" },
  { product: "Ege Akustik", ral: "9016", quantity: 820, date: "2026-02-27", shift: "Tag", notes: "" },
  { product: "Fenstergriff Standard", ral: "9016", quantity: 2300, date: "2026-02-27", shift: "Tag", notes: "" },
  { product: "Rollenlager Kunststoff", ral: "", quantity: 1200, date: "2026-02-27", shift: "Tag", notes: "" },
];
